Console.Write("Введите координату X точки A: ");
int Ax = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите координату Y точки A: ");
int Ay = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите координату Z точки A: ");
int Az = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите координату X точки B: ");
int Bx = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите координату Y точки B: ");
int By = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите координату z точки B: ");
int Bz = Convert.ToInt32(Console.ReadLine());
double distanse = Math.Round(Math.Sqrt(Math.Pow(Bx-Ax, 2)+Math.Pow(By-Ay, 2)+Math.Pow(Bz-Az, 2)), 2);
Console.Write(distanse);